feat: replace asdf with mise (#15)
1. Replaces [ASDF](https://asdf-vm.com) with [Mise](https://mise.jdx.dev) for managing virtual environments.
2. Moves the default location of the local laptop repository from `~/code/laptop` to `~/code/ssmereka/laptop`.
3. Added multiple languages, tools, and frameworks. See the updated readme.
4. Small updates to logging and documentation.

diff --git a/src/mac b/src/mac
--- a/src/mac
+++ b/src/mac
@@ -7,7 +7,7 @@
 code_directory="$HOME/code"
 
 # Directory where a local copy of the Laptop repository will be cloned and stored.
-laptop_repo_directory="$code_directory/laptop"
+laptop_repo_directory="$code_directory/ssmereka/laptop"
 
 # Directory where the Laptop source code is stored.
 laptop_src_directory="$laptop_repo_directory/src"
@@ -141,70 +141,11 @@ clone_laptop_repository() {
     fi
 }
 
-# Configure ASDF to manage Node.js and Ruby runtime versions.
-# Parameters:
-#   laptop_src_location: A local directory path or a remote URL for the Laptop source code
-#                        directory. Defaults to the "laptop_src_directory" variable.
-configure_asdf() {
-    laptop_src_location=${1:-"$laptop_src_directory"}
-
-    log_header "🔧 Configuring ASDF"
-
-    # Create a local ASDF configuration file, if one doesn't exist
-    # https://asdf-vm.com/manage/configuration.html#asdf-config-file
-    copy_file "$laptop_src_location/.asdfrc" "$laptop_local_directory/.asdfrc"
-    link_file "$laptop_local_directory/.asdfrc" "$HOME/.asdfrc"
-
-    # Create a local .default-gems file, if one doesn't exist.
-    # After Ruby is installed, the gems specified in this file will be installed.
-    # https://github.com/asdf-vm/asdf-ruby?tab=readme-ov-file#default-gems
-    copy_file "$laptop_src_location/.default-gems" "$laptop_local_directory/.default-gems"
-    link_file "$laptop_local_directory/.default-gems" "$HOME/.default-gems"
-
-    # Source the ASDF version manager
-    . $(brew --prefix asdf)/libexec/asdf.sh
-
-    # Install the lastest version of Node.js using ASDF
-    # https://github.com/asdf-vm/asdf-nodejs
-    log_header "🔧 Installing Node.js with ASDF"
-    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
-    asdf install nodejs latest
-    asdf global nodejs latest
-    log "\nUsing Node.js version $(node --version)"
-
-    # Install the lastest version of Python using ASDF
-    # https://github.com/asdf-community/asdf-python
-    log_header "🔧 Installing Python with ASDF"
-    asdf plugin-add python
-    asdf install python latest
-    asdf global python latest
-    log "\nUsing Python version $(python --version)"
-
-    # Install the latest version of Ruby using ASDF
-    # https://github.com/asdf-vm/asdf-ruby
-    log_header "🔧 Installing Ruby with ASDF"
-    asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
-    asdf install ruby latest
-    asdf global ruby latest
-    log "\nUsing Ruby version $(ruby --version)"
-
-    # Install the latest version of Go using ASDF
-    # https://github.com/asdf-community/asdf-golang?tab=readme-ov-file#asdf-golang
-    log_header "🔧 Installing Go"
-    asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
-    # Manually set this env varible to the non default value of "false". This will force go to use
-    # the exact versoins in .tool-versions and/or .go-version files. See
-    # https://github.com/asdf-community/asdf-golang?tab=readme-ov-file#version-selection
-    export ASDF_GOLANG_MOD_VERSION_ENABLED=false && asdf install golang latest
-    export ASDF_GOLANG_MOD_VERSION_ENABLED=false && asdf global golang latest
-    go_version=$(go version)
-    log "\nUsing Go version $go_version"
-}
 
 # Configure the 1Password GitHub CLI plugin so that it uses the Personal Access Token from
 # 1Password for authentication.
 configure_gh() {
-    log_header "Configuring GitHub CLI"
+    log_header "😸 Configuring GitHub CLI"
 
     if [[ ! -f "$HOME/.config/op/plugins/gh.json" ]]; then
         log "Signing into 1Password to retrieve the GitHub Personal Access Token"
@@ -265,6 +206,27 @@ configure_git() {
 
     # Symbolically link the .gitconfig to the proper location.
     link_file "$local_gitconfig" "$HOME/.gitconfig"  
+}
+
+# Configure Mise to use the Laptop configuration files.
+# Parameters:
+#   laptop_src_location: A local directory path or a remote URL for the Laptop source code
+#                        directory. Defaults to the "laptop_src_directory" variable.
+configure_mise() {
+    laptop_src_location=${1:-"$laptop_src_directory"}
+
+    log_header "🔧 Configuring Mise"
+
+    # Create a local Mise configuration file.
+    copy_file "$laptop_src_location/.mise_config.toml" "$laptop_local_directory/.mise_config.toml"
+    link_file "$laptop_local_directory/.mise_config.toml" "$HOME/.config/mise/config.toml"
+
+    # Create a local Default Gems file.
+    copy_file "$laptop_src_location/.default-gems" "$laptop_local_directory/.default-gems"
+    link_file "$laptop_local_directory/.default-gems" "$HOME/.default-gems"
+
+    # Trust the local configuration file to prevent prompts in the automated install.
+    mise trust "$HOME/.config/mise/config.toml" || true
 }
 
 # Configure SSH to use the SSH keys in 1Password.
@@ -344,14 +306,14 @@ copy_file() {
 
     if [[ $overwrite == true || ! -f "$destination" ]]; then
         if [[ "$source" == http* ]]; then
-            log "Downloading file from $source to $destination"
+            log "Downloading file from \"$source\" to \"$destination\""
             curl -o "$destination" "$source"
         else
-            log "Copying file from $source to $destination"
+            log "Copying file from \"$source\" to \"$destination\""
             cp "$source" "$destination"
         fi
     else
-        log "No changes to file at $destination."
+        log "No changes to file at \"$destination\"."
     fi
 }
 
@@ -380,7 +342,7 @@ get_secrets() {
     log "Unlocking the 1Password CLI."
     $(op signin)
     
-    log "Retrieving fields \"$field_name_git_email\", \"$field_name_git_name\", and " \
+    log "Retrieving fields \"$field_name_git_email\", \"$field_name_git_name\", and" \
         "\"$field_name_git_username\" from 1Password item \"$item_name_git\"."
     
     git_email=$(op item get "$item_name_git" --fields "$field_name_git_email")
@@ -418,14 +380,26 @@ install_apps() {
     log_header "🔧 Installing Homebrew Applications"
 
     brew bundle --file=- <<EOF
-    brew 'gh' # https://cli.github.com
-    brew 'asdf' # Requires coreutils, curl, and gawk, https://asdf-vm.com
-    brew 'coreutils' # https://formulae.brew.sh/formula/coreutils
-    brew 'curl' # https://curl.se
-    brew 'gawk' # https://www.gnu.org/software/gawk/
-    brew 'gnupg' # https://www.gnupg.org
     brew 'atuin' # https://atuin.sh
+    brew 'awscli' # https://docs.aws.amazon.com/cli/
+    brew 'curl' # https://curl.se
+    brew 'coreutils' # https://formulae.brew.sh/formula/coreutils
+    brew 'gawk' # https://www.gnu.org/software/gawk/
+    brew 'gh' # https://cli.github.com
+    brew 'gmp' # https://gmplib.org/
+    brew 'gnupg' # https://www.gnupg.org
+    brew 'libyaml' # https://pyyaml.org/wiki/LibYAML
+    brew 'mise' # https://mise.jdx.dev
+    brew 'openssl@3' # https://www.openssl.org/
+    brew 'postgresql' # https://www.postgresql.org
+    brew 'rustup-init' # https://rustup.rs
 EOF
+
+    # Initialize rustup with the default stable Rust toolchain non-interactively, if
+    # it's not already installed and configured.
+    if ! command -v rustup >/dev/null 2>&1; then
+        rustup-init -y
+    fi
 
     log_header "🔧 Installing Applications"
 
@@ -442,17 +416,21 @@ EOF
     else
         log "1Password CLI is already installed."
     fi
+
+    install_mise_tools
+    install_or_update_nvm
+
 }
 
 # Run the custom installation script if it exists on the local machine.
 install_custom() {
-    log_header "🪄 Running Customizations"
+    log_header "🪄  Running Customizations"
     if [[ -f "$laptop_custom_install_script" ]]; then
-        log "Running local customization script at $laptop_custom_install_script"
+        log "Running local customization script at \"$laptop_custom_install_script\""
         chmod +x "$laptop_custom_install_script"
         "$laptop_custom_install_script"
     else
-        log "No customizations found at $laptop_custom_install_script".
+        log "No customizations found at \"$laptop_custom_install_script\"."
     fi
 }
 
@@ -473,6 +451,47 @@ install_or_update_homebrew() {
     fi
 }
 
+# Installs NVM using the official install script from the NVM repository.
+# If NVM is already installed, it will update NVM to the latest version.
+# Verifies that NVM is installed and working by checking the version.
+install_or_update_nvm() {
+    log_header "🔧 Installing or updating Node Version Manager (NVM)"
+
+    # The PROFILE=/dev/null will prevent the setup script from updating
+    # the bash profile(s), as this is already configured by the Laptop script.
+    PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash'
+
+    # Load nvm for the current shell, if it is not already loaded.
+    local nvm_dir="${NVM_DIR:-${XDG_CONFIG_HOME:-$HOME/.nvm}}"
+    export NVM_DIR="$nvm_dir"
+    if [ -s "$NVM_DIR/nvm.sh" ]; then
+        . "$NVM_DIR/nvm.sh"
+    fi
+
+    # Verify that nvm is installed and working.
+    if command -v nvm >/dev/null 2>&1; then
+        echo "\n✅ Node Version Manager (NVM) version $(nvm --version) is installed."
+    else
+        echo "\n❌ Node Version Manager (NVM) installation failed.\n" >&2
+    fi
+}
+
+# Configures the mise global tools using the defined configuration file, then installs those tools.
+install_mise_tools() {
+    # Create the default global Mise configuration file, if it doesn't already exist
+    configure_mise
+
+    log_header "🔧 Installing Mise Tools"
+
+    # Add Cargo to the PATH, if it's not already there.
+    if ! echo "$PATH" | grep -q "$HOME/.cargo/bin"; then
+        export PATH="$HOME/.cargo/bin:$PATH"
+    fi
+
+    # Install all tools defined in Mise default global configuration
+    (cd "$HOME" && mise install --yes)
+}
+
 # Returns zero when the Laptop script is considered installed locally, otherwise returns one.
 is_laptop_installed() {
     if [ -d "$laptop_repo_directory" ]; then
@@ -491,7 +510,11 @@ link_file() {
     source="$1"
     destination="$2"
 
-    log "Creating a new symbolic link from $source to $destination"
+    # The "ln" command will fail if the directories in the destination 
+    # path do not exist. Create all the destination directories, if they do not exist.
+    mkdir -p "$(dirname "$destination")"
+
+    log "Creating a new symbolic link from \"$source\" to \"$destination\""
     ln -sf "$source" "$destination"
 }
 
@@ -561,7 +584,6 @@ install() {
     configure_ssh "$laptop_src_location"
     configure_git "$laptop_src_location"
     configure_zsh "$laptop_src_location"
-    configure_asdf "$laptop_src_location"
 
     configure_gh
 
@@ -580,11 +602,14 @@ uninstall() {
 
     log_header "🔨 Uninstalling Applications"
 
-    if brew list asdf &>/dev/null; then
-        brew uninstall asdf
-    fi
     if brew list atuin &>/dev/null; then
         brew uninstall atuin # https://atuin.sh
+    fi
+
+    uninstall_nvm
+
+    if brew list mise &>/dev/null; then
+        brew uninstall mise # https://mise.jdx.dev
     fi
 
     # TODO: Ask if you want to uninstall these
@@ -593,6 +618,7 @@ uninstall() {
     # brew uninstall curl
     # brew uninstall gawk
     # brew uninstall gnupg # https://www.gnupg.org
+    # rustup-init
 
     log_header "🗂️ Removing Application Data"
 
@@ -603,6 +629,16 @@ uninstall() {
     rm -rf "$HOME/.config/atuin"
 
     log "\n🎉 Done. Restart your shell to complete the uninstall."
+}
+
+# Removes NVM if it is installed.
+uninstall_nvm() {
+    local nvm_dir="${NVM_DIR:-${XDG_CONFIG_HOME:-$HOME/.nvm}}"
+    if [ -d "$nvm_dir" ]; then
+        echo "\n💥 Uninstalling Node Version Manager (NVM).\n"
+        command -v nvm >/dev/null && nvm unload
+        rm -rf "$nvm_dir"
+    fi
 }
 
 # Interprit commandline arguments and run the appropriate methods.
