Moved all user interactive steps to the front of the script

diff --git a/src/mac b/src/mac
--- a/src/mac
+++ b/src/mac
@@ -26,17 +26,83 @@ else
     exit 1
 fi
 
+# Secrets
+# The user's Git configuration details, including their email, name, and GitHub username.
+git_email=""
+git_name=""
+github_username=""
+
+# Prompt to inform the user that there are unsaved changes in the Laptop git repository.
+unsaved_changes_prompt='
+🤔 hmm... there are unsaved changes in the Laptop git repository.
+
+We can stash those local changes and pull the latest changes from the 
+remote repository. You would be able to reapply those local changes 
+by running the command:
+
+    cd '$laptop_repo_directory' && git stash pop 
+
+Or we can just proceed with using the current local version of Laptop.
+
+'
+
+# Clone the Laptop repository locally, if it doesn't exist locally
+clone_laptop_repository() {
+    if [[ ! -d "$laptop_repo_directory" ]]; then
+        mkdir -p $laptop_repo_directory
+        git clone git@github.com:ssmereka/laptop.git "$laptop_repo_directory"
+
+        if [[ ! -f "$laptop_repo_directory/mac" ]]; then
+            echo -e "\n🔴 Error:  Failed to clone Laptop to \"$laptop_repo_directory\".\n"
+            exit 1
+        fi
+    fi
+}
+
+# Configure ASDF to manage Node.js and Ruby runtime versions.
+configure_asdf() {
+    log "🔧 Configuring ASDF"
+
+    # Create a local ASDF configuration file, if one doesn't exist
+    # https://asdf-vm.com/manage/configuration.html#asdf-config-file
+    copy_src_file_and_symlink ".asdfrc" "$HOME/.asdfrc" false
+
+    # Create a local .default-gems file, if one doesn't exist.
+    # After Ruby is installed, the gems specified in this file will be installed.
+    # https://github.com/asdf-vm/asdf-ruby?tab=readme-ov-file#default-gems
+    copy_src_file_and_symlink ".default-gems" "$HOME/.default-gems" false
+
+    # Source the ASDF version manager
+    . $(brew --prefix asdf)/libexec/asdf.sh
+
+    # Install the lastest version of Node.js using ASDF
+    # https://github.com/asdf-vm/asdf-nodejs
+    log "🔧 Installing Node.js with ASDF"
+    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
+    asdf install nodejs latest
+    asdf global nodejs latest
+    print -- "Installed Node.js $(node --version)"
+
+    # Install the latest version of Ruby using ASDF
+    # https://github.com/asdf-vm/asdf-ruby
+    log "🔧 Installing Ruby with ASDF"
+    asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
+    asdf install ruby latest
+    asdf global ruby latest
+    print -- "Installed Ruby $(ruby --version)"
+
+    # Install the latest version of Go using ASDF
+    # https://github.com/asdf-community/asdf-golang?tab=readme-ov-file#asdf-golang
+    # log "🔧 Installing Go"
+    # asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
+    # asdf install golang latest
+    # asdf global golang latest
+    # print -- "Installed Go $(go version)"
+    
+}
 
 # Create a Git configuration file with the user's GitHub information from 1Password.
 configure_git() {   
-    log "🔐  Unlock 1Password"
-
-    # Get the user's GitHub information from 1Password
-    $(op signin)
-    git_email=$(op item get GitHub --fields email)
-    git_name=$(op item get GitHub --fields name)
-    github_username=$(op item get GitHub --fields username)
-
     log "🔧 Configuring Git"
 
     # Create a local Git configuration file from the Laptop template, if one doesn't exist.
@@ -92,48 +158,6 @@ configure_zsh() {
     copy_file "$laptop_src_directory/.zshrc_methods" "$laptop_local_directory/.zshrc_methods" true
 }
 
-# Configure ASDF to manage Node.js and Ruby runtime versions.
-configure_asdf() {
-    log "🔧 Configuring ASDF"
-
-    # Create a local ASDF configuration file, if one doesn't exist
-    # https://asdf-vm.com/manage/configuration.html#asdf-config-file
-    copy_src_file_and_symlink ".asdfrc" "$HOME/.asdfrc" false
-
-    # Create a local .default-gems file, if one doesn't exist.
-    # After Ruby is installed, the gems specified in this file will be installed.
-    # https://github.com/asdf-vm/asdf-ruby?tab=readme-ov-file#default-gems
-    copy_src_file_and_symlink ".default-gems" "$HOME/.default-gems" false
-
-    # Source the ASDF version manager
-    . $(brew --prefix asdf)/libexec/asdf.sh
-
-    # Install the lastest version of Node.js using ASDF
-    # https://github.com/asdf-vm/asdf-nodejs
-    log "🔧 Installing Node.js with ASDF"
-    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
-    asdf install nodejs latest
-    asdf global nodejs latest
-    print -- "Installed Node.js $(node --version)"
-
-    # Install the latest version of Ruby using ASDF
-    # https://github.com/asdf-vm/asdf-ruby
-    log "🔧 Installing Ruby with ASDF"
-    asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
-    asdf install ruby latest
-    asdf global ruby latest
-    print -- "Installed Ruby $(ruby --version)"
-
-    # Install the latest version of Go using ASDF
-    # https://github.com/asdf-community/asdf-golang?tab=readme-ov-file#asdf-golang
-    # log "🔧 Installing Go"
-    # asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
-    # asdf install golang latest
-    # asdf global golang latest
-    # print -- "Installed Go $(go version)"
-    
-}
-
 # Copy a file from the source path to the destination path if the file 
 # does not already exist. When "overwrite" is true, the file will be replaced.
 # Parameters:
@@ -170,17 +194,42 @@ copy_src_file_and_symlink() {
     ln -sf "$local_default_gems_path" "$default_location"
 }
 
+# Get secrets from 1Password and store them in global variables
+get_secrets() {
+    log "🔐  Unlock 1Password"
+
+    # Get the user's GitHub information from 1Password
+    $(op signin)
+    git_email=$(op item get GitHub --fields email)
+    git_name=$(op item get GitHub --fields name)
+    github_username=$(op item get GitHub --fields username)
+}
+
 # Install applications using Homebrew
 install_apps() {
     # Install applications using Homebrew
     brew bundle --file=- <<EOF
-    cask '1password-cli'
     brew 'gh'
-    brew 'asdf' # Requires coreutils, gawk, curl
+    brew 'asdf' # Requires coreutils, curl, and gawk
     brew 'coreutils'
     brew 'curl'
     brew 'gawk'
 EOF
+}
+
+install_custom() {
+    if [[ -f "$laptop_custom_install_script" ]]; then
+        log "🪄  Running your customizations from $laptop_custom_install_script"
+        chmod +x "$laptop_custom_install_script"
+        "$laptop_custom_install_script"
+    else
+        log "🪄  No customizations found at $laptop_custom_install_script"
+    fi
+}
+
+install_onepassword_cli() {
+    log "🔧 Installing 1Password CLI"
+    brew install --cask 1password-cli
 }
 
 # Install and configure the user's PATH to include Homebrew. Or update 
@@ -200,40 +249,10 @@ install_or_update_homebrew() {
     fi
 }
 
-install_custom() {
-    if [[ -f "$laptop_custom_install_script" ]]; then
-        log "🪄  Running your customizations from $laptop_custom_install_script"
-        chmod +x "$laptop_custom_install_script"
-        "$laptop_custom_install_script"
-    else
-        log "🪄  No customizations found at $laptop_custom_install_script"
-    fi
+
+log() {
+    print -- "\n→ "$1"\n"
 }
-
-clone_laptop_repository() {
-    # Clone the Laptop repository if it doesn't exist locally
-    if [[ ! -d "$laptop_repo_directory" ]]; then
-        mkdir -p $laptop_repo_directory
-        git clone git@github.com:ssmereka/laptop.git "$laptop_repo_directory"
-
-        if [[ ! -f "$laptop_repo_directory/mac" ]]; then
-            echo -e "\n🔴 Error:  Failed to clone Laptop to \"$laptop_repo_directory\".\n"
-            exit 1
-        fi
-    fi
-}
-
-unsaved_changes_prompt='
-🤔 hmm... there are unsaved changes in the Laptop git repository.
-
-We can stash those local changes and pull the latest changes from the 
-remote repository. You would be able to reapply those local changes 
-by running the command:
-
-    cd '$laptop_repo_directory' && git stash pop 
-
-Or we can just proceed with using the current local version of Laptop.
-'
 
 update_laptop_repository() {
     pushd $laptop_repo_directory > /dev/null
@@ -252,7 +271,7 @@ update_laptop_repository() {
             log "💾  Stashing Local Changes"
             git stash
         else
-            print -- "\n OK, we will skip pulling the latest changes.\n"
+            print -- "\nOK, we will skip pulling the latest changes.\n"
             return
         fi
     fi
@@ -265,15 +284,14 @@ update_laptop_repository() {
     popd > /dev/null
 }
 
-log() {
-    print -- "\n→ "$1"\n"
-}
-
 main() {
-    print -- "\n💻 Install Laptop\n\n Don't go anywhere yet, we may have some questions.\n"
+    print -- "\n💻 Installing Laptop\n\nDon't go anywhere just yet, we may need you!\n--------------------------------------------\n"
 
     clone_laptop_repository
     update_laptop_repository
+
+    install_onepassword_cli
+    get_secrets
 
     print -- "\n🚀 Ok, we got this! Setting up your laptop ...time for a 🚬 smoke break?\n"
     install_or_update_homebrew
